openapi: 3.0.2
info:
  title: FDK User API
  description: Exposes a basic service which provides information related to FDK users
  version: '1.0'
  termsOfService: 'https://fellesdatakatalog.digdir.no/about'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://fellesdatakatalog.digdir.no'
    email: fellesdatakatalog@digdir.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
externalDocs:
  description: Dokumentasjon på Informasjonsforvaltning GitHub
  url: https://informasjonsforvaltning.github.io
tags:
  - name: users
    description: Users from the National Data Directory
  - name: authorities
    description: User FDK authorities
servers:
  - url: 'https://fellesdatakatalog.digdir.no'
paths:
  /users/{id}:
    get:
      tags:
        - users
      summary: Get user info.
      description: Returns user info
      operationId: getUserInfo
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '404':
          description: No corresponding user found with id
  /authorities/altinn/{id}:
    get:
      tags:
        - authorities
      description: Get user authorities for users from the altinn identity provider
      operationId: getAltinnAuthorities
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '404':
          description: User not found
  /authorities/difi:
    get:
      tags:
        - authorities
      description: Get user authorities for users from the difi identity provider
      operationId: getDifiAuthorities
      parameters:
        - name: roles
          in: query
          description: difi roles
          required: true
          schema:
            type: array
            items:
              type: string
        - name: orgs
          in: query
          description: organization numbers
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /terms/altinn/{id}:
    get:
      tags:
        - terms
      description: Get the accepted version of FDK terms for organizations associated with the user
      operationId: getOrgTermsAltinn
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '404':
          description: User not found
  /terms/difi:
    get:
      tags:
        - terms
      description: Get the accepted version of FDK terms for organizations associated with the user
      operationId: getOrgTermsDifi
      parameters:
        - name: orgs
          in: query
          description: organization numbers
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    User:
      type: object
      description: A user
      properties:
        id:
          type: string
          description: User id
        firstName:
          type: string
          description: Given name
        lastName:
          type: string
          description: Family name
