openapi: 3.0.2
info:
  title: National Data Directory User API
  description: Exposes a basic service which provides information related to users in the National Data Directory
  version: '1.0'
  termsOfService: 'https://fellesdatakatalog.brreg.no/about'
  contact:
    name: Brønnøysundregistrene
    url: 'https://fellesdatakatalog.brreg.no'
    email: fellesdatakatalog@brreg.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
externalDocs:
  description: Dokumentasjon på Informasjonsforvaltning GitHub
  url: https://informasjonsforvaltning.github.io/felles-datakatalog/datasett-katalog/api/
tags:
  - name: user-api
    description: User API
servers:
  - url: 'https://fellesdatakatalog.brreg.no'
paths:
  /users/{id}:
    get:
      tags:
        - user-api
      summary: Get user info.
      description: Returns user info
      operationId: getUserInfo
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: User
  /authorities/{id}:
    get:
      tags:
        - user-api
      description: Get user authorities
      operationId: getAuthorities
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    User:
      type: object
      description: A user
      properties:
        id:
          type: string
          description: User id
        firstName:
          type: string
          description: Given name
        lastName:
          type: string
          description: Family name
