spring:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:INFO}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  hosts:
    altinnProxyHost: ${ALTINN_PROXY_HOST:http://fdk-nginx-altinn-proxy:8080}
    termsHost: ${TERMS_AND_CONDITIONS_HOST:http://terms-and-conditions:8080}
  whitelists:
    # 920210023   /* this matches in prod system "GJELDSREGISTERET AS”*/
    # 910258028   /* this matches in mock data "LILAND OG ERDAL REVISJON", used in dev, ut1, st1 and it1*/
    orgNrWhitelist: ${ORGNR_WHITELIST:920210023,910258028,910244132}
    orgFormWhitelist: ${ORGFORM_WHITELIST:ADOS,FKF,FYLK,IKS,KF,KIRK,KOMM,ORGL,SF,STAT,SÆR}
    adminList: ${ADMIN_LIST:23076102252} #MAUD GULLIKSEN
  secrets:
    ssoApiKey: ${SSO_API_KEY}
    userApiKey: ${USER_API_KEY}
    altinnProxyKey: ${ALTINN_PROXY_API_KEY}
  brreg:
    orgnr: ${ORGNR_BRREG:974760673}
    adminGroupID: ${ADMIN_GROUP_BRREG:123}
    writeGroupID: ${WRITE_GROUP_BRREG:321,222}
  skatt:
    orgnr: ${ORGNR_SKATT:974761076}
    adminGroupID: ${ADMIN_GROUP_SKATT:123}
    writeGroupID: ${WRITE_GROUP_SKATT:321}
    readGroupID: ${READ_GROUP_SKATT:111}
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        info: ping
        health: ready
      exposure:
        include: health, info
  metrics:
    tags:
      application: user-api
server:
  port: 8080
  servlet.session.timeout: 1m
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 1m

---
#Utv-miljø lokalt på egen PC
spring:
  config.activate.on-profile: develop
application:
  hosts:
    altinnProxyHost: http://localhost:8128
    termsHost: http://localhost:8182
  secrets:
    ssoApiKey: ssosecret
    userApiKey: userapisecret
    altinnProxyKey: proxysecret
server.port: 8125

---
spring:
  config.activate.on-profile: contract-test
application:
  hosts:
    altinnProxyHost: http://localhost:5555/altinn
    termsHost: http://localhost:5555/terms
  whitelists:
    adminList: ${ADMIN_LIST:10987654321}
    orgNrWhitelist: ${ORGNR_WHITELIST:920210023,910258028,123456789}
  secrets:
    ssoApiKey: ssosecret
    userApiKey: userapisecret
    altinnProxyKey: proxysecret
server.port: 5050
