---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - user-api-deployment.yaml
  - user-api-service.yaml
images:
  - name: user-api
    newName: ghcr.io/informasjonsforvaltning/user-api
    newTag: $(GIT_COMMIT_SHA)
