---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fdk.service: user-api
  name: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: user-api
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        fdk.service: user-api
    spec:
      containers:
        - name: user-api
          image: user-api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "500Mi"
              cpu: "10m"
            limits:
              memory: "500Mi"
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
      restartPolicy: Always
